CREDENTIALS = {
    'DISCORD_TOKEN': 'YOUR DISCORD TOKEN HERE',
    'REDDIT_API_CLIENT_ID': 'YOUR REDDIT API CLIENT ID HERE',
    'REDDIT_API_CLIENT_SECRET': 'YOUR REDDIT API CLIENT SECRET HERE',
    #'RAPID_API_KEY': ''
}

def get_credentials(key):
	return CREDENTIALS[key]
